### PR TITLE
GHA-65 Update package-lock.json

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**
[GHA-65](https://sonarsource.atlassian.net/browse/GHA-65)

Result of deleting `node_modules` and running `npm install`, as I had some issues building the project locally

> Cannot find type definition file for 'node'

[GHA-65]: https://sonarsource.atlassian.net/browse/GHA-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by sebastien-marichal — CHANGES_REQUESTED** [review]
Not sure why, if I do it locally, it seems that my `npm install` is getting rid of all the `license`:
image


What I did:

- `rm -Recurse node_modules`
- Comment `/node_modules/` in .gitignore
- `npm install --omit=dev`

**Review by sebastien-marichal — CHANGES_REQUESTED** [review]
After updating to 10.9.0 (I was on 10.2.4), I don't have the issue anymore.
However, it seems the `node_modules/.package-lock.json` still contains dev dependency.
When I do an update locally, I get a huge part of the file deleted and all the dependencoes seem to have a `"dev": true` field.

**Review by sebastien-marichal — APPROVED** [review]
LGTM!
